name: Build FAISS Index (Manual Trigger)

on:
  workflow_dispatch:

jobs:
  run-index-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          cd model_pipeline/voice-backend
          pip install -r requirements.txt

      - name: Decode and Write GCP Credentials File
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > gcp_key.json
        shell: bash

      - name: Build FAISS Index
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_key.json
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd model_pipeline/voice-backend
          python build-faiss-index.py

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Upload FAISS Index to GCP
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: model_pipeline/voice-backend/faiss_index.index
          destination: /speaking-chatbot-data/vectors/
          process_gcloudignore: false

      - name: Upload Metadata to GCP
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: model_pipeline/voice-backend/index_metadata.json
          destination: /speaking-chatbot-data/vectors/
          process_gcloudignore: false
