name: Deploy to Cloud Run & Firebase

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Flask to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: speakingbot-backend
          region: us-central1
          source: ./model_pipeline/voice-backend

  deploy-frontend:
    name: Deploy React to Firebase Hosting
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build React App
        run: |
          cd model_pipeline
          npm ci
          npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.2.1
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


        run-model-validation:
    name: Run Model Validation Job
    runs-on: ubuntu-latest
    steps:
      - name: Auth with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Trigger Cloud Run Job
        run: |
          gcloud run jobs execute model-validation-job \
            --region us-central1 \
            --project mlops-speakingchatbot \
            --wait

  run-bias-detection:
    name: Run Bias Detection Job
    runs-on: ubuntu-latest
    needs: run-model-validation
    steps:
      - name: Auth with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Trigger Cloud Run Job
        run: |
          gcloud run jobs execute bias-detection-job \
            --region us-central1 \
            --project mlops-speakingchatbot \
            --wait
