name: Model Pipeline CI/CD

on:
  push:
    paths:
      - 'model_pipeline/**'
  pull_request:
    paths:
      - 'model_pipeline/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          cd model_pipeline/voice-backend
          pip install -r requirements.txt

      - name: Run Model Validation
        run: |
          cd model_pipeline/voice-backend
          python model_validation.py

      - name: Run Bias Detection
        run: |
          cd model_pipeline/voice-backend
          python bias_detection.py

      - name: Run Tests
        run: |
          cd model_pipeline/voice-backend/tests
          pytest test_app.py

      - name: Run Flask App Check
        run: |
          cd model_pipeline/voice-backend
          python app.py &
          sleep 10
          curl http://localhost:5000 || echo "App not reachable"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run React Dev Build
        run: |
          cd model_pipeline/src
          npm install
          npm run build
