version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: airflow_container
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./tests:/opt/airflow/tests
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
    ports:
      - "8080:8080"
      - "8793:8793"
    command: webserver